[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
]
dynamic = ["version"]
name = "elabaugus"

[project.scripts]
elabaugus = "elabaugus.main:main"